### PR TITLE
Add user to flow storage

### PR DESCRIPTION
**Pull request by hardillb**
part of FlowFuse/flowfuse#4413

## Description

Passes the user who is doing the deploy to FlowFuse Storage backend

## Related Issue(s)

FlowFuse/flowfuse#4413

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Ben, as mentioned in the parent issue [comment](https://github.com/FlowFuse/flowfuse/issues/4413#issuecomment-2364297279), PR [#4530](https://github.com/FlowFuse/flowfuse/pull/4530) has been raised. That PR may supersede this PR but I am not 100% certain this isn't worth doing also?

**Comment by Steve-Mcl** [comment]
Ben, I know this is no longer an absolute requirement for the original issue, but I can see a future where this would be useful.

Should we merge or put it in draft for the time being?

**Comment by hardillb** [comment]
Let's put it in draft until we decide if we need it

**Comment by knolleary** [comment]
As this may become useful again for https://github.com/FlowFuse/flowfuse/issues/4791 - so am going to pull out of draft and get merged. Even if we don't make use of it immediately, given it requires stack updates for instances to pickup, the sooner we have it out there, the sooner we can rely on it.

**Review by knolleary — APPROVED** [review]
Sadly this is the only function on the API that receives user info from Node-RED - otherwise we'd want to add this header to them all for future proofing.

Have tested locally and it does the job.

**Pull request merged**
